[package]
name = "replace-all"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Parse command line argument by defining a struct.
structopt = "0.3.26"

